spring.application.name=journal-App

# mongodb
spring.data.mongodb.uri=mongodb+srv://username:password@cluster01.c99ynxc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster01
spring.data.mongodb.database=journaldb
#this is for indexing
spring.data.mongodb.auto-index-creation=true
